// Core schema for the locked pipeline:
// Story Engine (Claude) -> Character Sheet (Banana Pro) -> H3 Reference-to-Video -> ffmpeg assembly

export interface CharacterReference {
  id: string;
  name: string;
  appearance: string; // locked physical description, used as fallback / prompt text
  personalityNote: string;
  voiceOnly?: boolean; // true for characters never seen on screen (voice/phone/offscreen only)

  // Visual reference: auto-generated by /api/character-sheet (Banana 2).
  // Skipped for voiceOnly characters.
  imageReferenceUrls: string[];

  // Voice reference: the piece Golden Soul's current UI can't test.
  // A short clip (5-15s) of the character's voice/delivery for H3's voice referencing.
  voiceReferenceUrl?: string;
  voiceReferenceNote?: string; // fallback text description if no clip yet, e.g. "low, controlled, faint rasp"
}

export interface CameraDirection {
  angle: string; // e.g. "wide static shot", "medium close-up"
  movement: string; // e.g. "none", "slow push-in", "slow pull-back"
}

export interface DialogueLine {
  characterId: string;
  line: string;
  delivery: string; // tone/pacing instruction, e.g. "flat, controlled"
}

export interface SceneJob {
  sceneId: number;
  setting: string;
  sceneDescription: string;
  camera: CameraDirection;
  colorGrade: string;
  dialogue: DialogueLine[];
  soundFx: string[];
  musicCue: string;

  // Render config for this specific scene
  durationSeconds?: number; // 5-15s per H3 limits
  resolutionTier?: "480p" | "540p" | "768p" | "2k";
  useVoiceReference?: boolean; // the A/B toggle: render with vs. without voice ref
}

export interface StoryPackage {
  storyId: string;
  title: string;
  genre: string;
  premise: string;
  tone: "dark" | "neutral" | "uplifting";
  targetLengthSeconds: 30 | 60 | 90 | 180;
  seriesContext?: { episodeNumber: number; priorEpisodeSummary: string };
  hookNote?: string;
  loopEndingNote?: string;
  manualOutline?: string;
  brandEmbed?: { brandName: string; logoImageUrl?: string };
  characters: CharacterReference[];
  scenes: SceneJob[];
  createdAt: string;
}

export interface RenderResult {
  sceneId: number;
  status: "pending" | "rendering" | "complete" | "failed";
  videoUrl?: string;
  errorMessage?: string;
  usedVoiceReference: boolean;
  costEstimateUsd?: number;
}

// Builds the H3 reference-to-video prompt.
// Each character gets an explicit Image N / Audio N binding in the header,
// and that binding is restated on every dialogue line so H3 never confuses speakers.
// brandEmbed is optional — logo reference injected only when brand appears in scene.
export function buildH3Prompt(
  scene: SceneJob,
  characters: CharacterReference[],
  brandEmbed?: { brandName: string; logoImageUrl?: string }
): string {
  const involvedIds = new Set(scene.dialogue.map((d) => d.characterId));
  const involvedChars = characters.filter((c) => involvedIds.has(c.id));

  // Visual chars only — voice-only characters have no image slot.
  const visualChars = involvedChars.filter((c) => c.imageReferenceUrls.length > 0);

  // Build a lookup: characterId → { imageIdx, audioIdx }
  // audioIdx is only assigned when the character has a voiceReferenceUrl.
  let audioCounter = 0;
  const charBinding = new Map<string, { imageIdx: number; audioIdx: number | null }>();
  visualChars.forEach((c, i) => {
    const hasAudio = !!c.voiceReferenceUrl;
    charBinding.set(c.id, {
      imageIdx: i + 1,
      audioIdx: hasAudio ? ++audioCounter : null,
    });
  });

  // Header: one line per character declaring both bindings explicitly.
  const charRefLines = visualChars.map((c) => {
    const b = charBinding.get(c.id)!;
    const imageLine = `Use Image ${b.imageIdx} as the visual reference for ${c.name}. Preserve appearance: ${c.appearance}.`;
    const audioLine = b.audioIdx !== null
      ? `Use Audio ${b.audioIdx} as the voice reference for ${c.name}.`
      : null;
    return [imageLine, audioLine].filter(Boolean).join(" ");
  }).join("\n");

  // Logo reference slot (after character images).
  const logoImageIdx = visualChars.length + 1;
  const logoRefLine =
    brandEmbed?.logoImageUrl &&
    scene.sceneDescription.toLowerCase().includes(brandEmbed.brandName.toLowerCase())
      ? `Use Image ${logoImageIdx} as the exact logo reference for ${brandEmbed.brandName}. Reproduce it precisely where it appears in the scene, unaltered.`
      : "";

  const referenceLines = [charRefLines, logoRefLine].filter(Boolean).join("\n");

  // Dialogue: restate image/audio binding on every line so H3 keeps voices separated.
  const dialogueLines = scene.dialogue.map((d) => {
    const speaker = characters.find((c) => c.id === d.characterId);
    const b = speaker ? charBinding.get(speaker.id) : undefined;
    const refTag = b
      ? b.audioIdx !== null
        ? `(Image ${b.imageIdx} / Audio ${b.audioIdx})`
        : `(Image ${b.imageIdx})`
      : "";
    return `${speaker?.name ?? d.characterId} ${refTag} speaks, delivered ${d.delivery}: "${d.line}"`;
  }).join("\n");

  return [
    referenceLines,
    "",
    `${scene.setting}. ${scene.sceneDescription}`,
    `Camera: ${scene.camera.angle}, ${scene.camera.movement}.`,
    `Color grade: ${scene.colorGrade}.`,
    "",
    dialogueLines,
    "",
    `ambient_sound: ${scene.soundFx.join(", ")}.`,
    `non_diegetic_music: ${scene.musicCue}, continuous under the scene, mixed beneath the dialogue.`,
  ].join("\n");
}
