// Core schema for the locked pipeline:
// Story Engine (Claude) -> Character Sheet (Banana Pro) -> H3 Reference-to-Video -> ffmpeg assembly

export interface CharacterReference {
  id: string;
  name: string;
  appearance: string; // locked physical description, used as fallback / prompt text
  personalityNote: string;
  voiceOnly?: boolean; // true for characters never seen on screen (voice/phone/offscreen only)

  // Visual reference: auto-generated by /api/character-sheet (Banana 2).
  // Skipped for voiceOnly characters.
  imageReferenceUrls: string[];

  // Voice reference: the piece Golden Soul's current UI can't test.
  // A short clip (5-15s) of the character's voice/delivery for H3's voice referencing.
  voiceReferenceUrl?: string;
  voiceReferenceNote?: string; // fallback text description if no clip yet, e.g. "low, controlled, faint rasp"
}

export interface CameraDirection {
  angle: string; // e.g. "wide static shot", "medium close-up"
  movement: string; // e.g. "none", "slow push-in", "slow pull-back"
}

export interface DialogueLine {
  characterId: string;
  line: string;
  delivery: string; // tone/pacing instruction, e.g. "flat, controlled"
}

export interface SceneJob {
  sceneId: number;
  setting: string;
  sceneDescription: string;
  camera: CameraDirection;
  colorGrade: string;
  dialogue: DialogueLine[];
  soundFx: string[];
  musicCue: string;

  // Render config for this specific scene
  durationSeconds?: number; // 5-15s per H3 limits
  resolutionTier?: "480p" | "540p" | "768p" | "2k";
  useVoiceReference?: boolean; // the A/B toggle: render with vs. without voice ref
}

export interface StoryPackage {
  storyId: string;
  title: string;
  genre: string;
  premise: string;
  tone: "dark" | "neutral" | "uplifting";
  targetLengthSeconds: 30 | 60 | 90 | 180;
  seriesContext?: { episodeNumber: number; priorEpisodeSummary: string };
  hookNote?: string;
  loopEndingNote?: string;
  manualOutline?: string;
  brandEmbed?: { brandName: string; logoImageUrl?: string };
  characters: CharacterReference[];
  scenes: SceneJob[];
  createdAt: string;
}

export interface RenderResult {
  sceneId: number;
  status: "pending" | "rendering" | "complete" | "failed";
  videoUrl?: string;
  errorMessage?: string;
  usedVoiceReference: boolean;
  costEstimateUsd?: number;
}

// Builds the "Use Image 1 as the locked character reference..." style prompt
// H3's reference-to-video mode expects, from a scene + its characters.
// brandEmbed is optional — when logoImageUrl is present and the brand name appears
// in the scene description, a logo reference line is appended after character refs.
export function buildH3Prompt(
  scene: SceneJob,
  characters: CharacterReference[],
  brandEmbed?: { brandName: string; logoImageUrl?: string }
): string {
  const involvedIds = new Set(scene.dialogue.map((d) => d.characterId));
  const involvedChars = characters.filter((c) => involvedIds.has(c.id));

  // Only include reference lines for characters that have images attached.
  // Voice-only characters (empty imageReferenceUrls) are skipped so H3 doesn't
  // receive a nonsensical "Preserve: Voice only..." visual instruction.
  const visualChars = involvedChars.filter((c) => c.imageReferenceUrls.length > 0);
  const charRefLines = visualChars
    .map((c, i) => `Use Image ${i + 1} as the locked character reference for ${c.name}. Preserve: ${c.appearance}.`)
    .join("\n");

  // Logo reference — only injected when a logo URL is provided AND the brand name
  // appears in this scene's description (so we don't waste a reference slot on
  // scenes where the brand isn't visible).
  const logoRefLine =
    brandEmbed?.logoImageUrl &&
    scene.sceneDescription.toLowerCase().includes(brandEmbed.brandName.toLowerCase())
      ? `Use Image ${visualChars.length + 1} as the exact logo reference for ${brandEmbed.brandName}. Reproduce it precisely where it appears in the scene, unaltered.`
      : "";

  const referenceLines = [charRefLines, logoRefLine].filter(Boolean).join("\n");

  const dialogueLines = scene.dialogue
    .map((d) => {
      const speaker = characters.find((c) => c.id === d.characterId);
      return `${speaker?.name ?? d.characterId} speaks, delivered ${d.delivery}: "${d.line}"`;
    })
    .join("\n");

  return [
    referenceLines,
    "",
    `${scene.setting}. ${scene.sceneDescription}`,
    `Camera: ${scene.camera.angle}, ${scene.camera.movement}.`,
    `Color grade: ${scene.colorGrade}.`,
    "",
    dialogueLines,
    "",
    `Ambient sound: ${scene.soundFx.join(", ")}.`,
    `Music: ${scene.musicCue}.`
  ].join("\n");
}
